Repository oauth-xx/oauth2, pull requests merged in 2018-03, with the labels that each got.

#362 Add SemVer and PVC to README
  README.md
Labels: docs

#364 Handle hal+json response format
  lib/oauth2/response.rb
  spec/oauth2/response_spec.rb
Labels: feature request

#335 Clean Changelog for 2.0.0 Release
  CHANGELOG.md
Labels: docs

#339 CI stability and Coveralls
  .travis.yml
  CHANGELOG.md
  spec/helper.rb
Labels: help wanted

#365 Handle collection+json
  lib/oauth2/response.rb
  spec/oauth2/response_spec.rb
Labels: feature request

#366 Fix logging via OAUTH_DEBUG=true to log both request and response, in…
  .rubocop_rspec.yml
  CHANGELOG.md
  README.md
  lib/oauth2/client.rb
  spec/helper.rb
  spec/oauth2/client_spec.rb
  spec/spec_helpers/stubbed_env.rb
Labels: feature request
