Repository oauth-xx/oauth2, pull requests merged in 2022-06, with the labels that each got.

#589 Drop support for MAC tokens
  .rubocop_todo.yml
  lib/oauth2.rb
  lib/oauth2/client.rb
  lib/oauth2/mac_token.rb
  spec/oauth2/mac_token_spec.rb
Labels: MAC

#587 use SHA256 digest
  lib/oauth2/mac_token.rb
Labels: feature request

#616 613/prepare 2.0.3
  CHANGELOG.md
  README.md
  lib/oauth2/version.rb
Labels: housekeeping
